name: CI

on:
  push:
    branches: ['master']
    tags:
      - '^v[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # trayendo el ultimo commit
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16
      # Runs a single command using the runners shell
      - name: First message
        run: echo Hello, world!

      - name: Install dependencies
        run: yarn install

      - name: build
        run: yarn build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL}}
